server:
  port: 8081
spring:
  application:
    name: sc-user-service # 应用名称，会在Eureka中显示
  datasource:
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10

mybatis:
  type-aliases-package: com.sumao.user.pojo

eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka  #,http://127.0.0.1:10087/eureka
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
    lease-expiration-duration-in-seconds: 10 # 10秒即过期
    lease-renewal-interval-in-seconds: 5 # 5秒一次心跳
    instance-id: ${spring.application.name}:${server.port}